using AutoMapper;
using Microsoft.AspNetCore.Http.HttpResults;
using NIFTWebApp.Modules.CarouselModule.DTOs;
using NIFTWebApp.Modules.CarouselModule.Entities;

namespace NIFTWebApp.Modules.CarouselModule.Mappings
{
    public class CarouselCardProfile : Profile
    {
        public CarouselCardProfile()
        {
            CreateMap<CarouselCard, CarouselCardDto>();
            CreateMap<CarouselCardDto, CarouselCard>();

            // Create DTO -> Entity
            CreateMap<CreateCarouselCardDto, CarouselCard>()
                .ForMember(dest => dest.imgURL, opt => opt.Ignore()) // handled manually in controller
                .ForMember(dest => dest.CarouselId, opt => opt.Ignore()); // auto-generated by DB

            // Update DTO -> Entity (if you add UpdateCarouselCardDto later)
            CreateMap<UpdateCarouselCardDto, CarouselCard>()
                .ForMember(dest => dest.imgURL, opt => opt.Ignore()) // handled separately
                .ForMember(dest => dest.CarouselId, opt => opt.Ignore()); // don't map the ID


        }
    }
}
